---
# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

# NOTE| The namespace of the collection.
namespace: "snapp"

# NOTE| The name of the collection.
name: "soe_utils"

# NOTE| The version of the collection.
version: "1.0.0"

# The path to the Markdown (.md) readme file.
readme: README.md

# NOTE| A list of the collection's content authors.
authors:
  - "snapp@redhat.com"

# NOTE| A short summary description of the collection.
description: "Standard Operating Environment Utilities"

# NOTE| Either a single license or a list of licenses for content inside of a collection.
# license:
#   - "GPL-3.0-or-later"

# NOTE| The path to the license file for the collection.
license_file: "LICENSE"

# NOTE| A list of tags you want to associate with the collection for indexing/searching.
tags:
  - "tools"

# NOTE| The list of collection dependencies this collection requires to be installed for it to be usable.
# dependencies: {}

# NOTE| The URL of the originating SCM repository
repository: "https://github.com/snapp/ansible-collection-soe_utils"

# NOTE| The URL to any online docs
# documentation: "https://github.com/snapp/ansible-collection-soe_utils/wiki"

# NOTE| The URL to the homepage of the collection/project
# homepage: "https://github.com/snapp/ansible-collection-soe_utils"

# NOTE| The URL to the collection issue tracker
issues: "https://github.com/snapp/ansible-collection-soe_utils/issues"

# NOTE| The build ignore list that should not be included in the build artifact.
build_ignore:
  - .gitignore
  - .github
  - '*/.gitkeep'
  - .pre-commit-config.yaml
  - .vscode
  - extensions

# A dict controlling use of manifest directives used in building the collection artifact.
# manifest: null
