---
# https://ansible.readthedocs.io/projects/molecule/configuration/#molecule.provisioner.ansible.Ansible.converge

- name: "Converge snapp.soe_utils.{{ playbook }}"
  ansible.builtin.import_playbook: "../../../../playbooks/{{ playbook }}.yml" # noqa: syntax-check[missing-file]
  vars:
    become: false
    ansible_become_method: su
    target: molecule
    playbook:
